services:
  - type: web
    name: swift-mtsaas-backend
    runtime: docker
    rootDir: backend
    plan: free
    region: ohio
    autoDeploy: true
    dockerfilePath: Dockerfile
    healthCheckPath: /api/v1/health
    healthCheckInterval: 600
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SERVER_SERVLET_CONTEXT_PATH
        value: /
    commands:
      build: mvn clean package -DskipTests
      start: java -jar target/backend-0.0.1-SNAPSHOT.jar

crons:
  - id: keep-alive
    schedule: "*/10 * * * *"
    httpMethod: GET
    httpPath: /api/v1/health
